# Generated by Django 2.2.7 on 2019-12-28 13:09

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('weather_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2019, 12, 28, 13, 9, 31, 492483, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
